language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r requirements.txt

script: make test
after_success: make deploy
